# Main Configuration (Required)
url         : http://lrvick.net
title       : Lance R. Vick
subtitle    : Life. Love. Tech... and other stuff.
description : The personal website and blog of Lance R. Vick, Head of Web Operations at Pebble Technology
author      : Lance R. Vick
email       : lance@lrvick.net
paginate    : 7

# Disqus Commenting
disqus_shortname : lrvick

# Google Analytics
google_analytics_id :
