# Main Configuration (Required)
url         : http://lrvick.net
title       : Lance R. Vick
subtitle    : I type in terminals and make things.
description : The personal website and blog of Lance R. Vick
author      : Lance R. Vick
email       : lance@lrvick.net
paginate    : 7

# Disqus Commenting
disqus_shortname : lrvick

# Google Analytics
google_analytics_id :
